export const SET_POKEMON_LIST = 'SET_POKEMON_LIST';
export const SET_FILTERED_POKEMON_LIST = 'SET_FILTERED_POKEMON_LIST';
export const SET_SELECTED_POKEMON = 'SET_SELECTED_POKEMON';
export const SET_SELECTED_POKEMONS = 'SET_SELECTED_POKEMONS';
export const SET_VIEWED_POKEMONS = 'SET_VIEWED_POKEMONS';
export const SET_SELECTED_TYPE = 'SET_SELECTED_TYPE';
export const SET_SHOW_MODAL = 'SET_SHOW_MODAL';

